version: '3.2'

services:
  ml4t-jup:
      image: ml4t:latest
      working_dir: /usr/src/app
      command: bash -c "jupyter notebook --no-browser --ip=0.0.0.0 --port=8888 --allow-root"
      volumes:
      - ./:/usr/src/app
      ports:
          - "127.0.0.1:8888:8888"
